/*
 * generated by Xtext
 */
package org.specapi.ui.contentassist

import org.specapi.ui.contentassist.AbstractSpecApiLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SpecApiLangProposalProvider extends AbstractSpecApiLangProposalProvider {
}
