/*
 * generated by Xtext
 */
package org.specapi.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.specapi.ui.internal.SpecApiLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpecApiLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SpecApiLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SpecApiLangActivator.getInstance().getInjector(SpecApiLangActivator.ORG_SPECAPI_SPECAPILANG);
	}
	
}
