/*
* generated by Xtext
*/
package org.specapi;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SpecApiLangUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.specapi.ui.internal.SpecApiLangActivator.getInstance().getInjector("org.specapi.SpecApiLang");
	}
	
}
