/*
 * generated by Xtext
 */
package org.specapi;

import org.eclipse.xtext.generator.OutputConfigurationProvider;
import org.specapi.plugins.PluginLoader;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpecApiLangRuntimeModule extends org.specapi.AbstractSpecApiLangRuntimeModule {
	
	public Class<? extends org.specapi.ModelUtil> bindModelUtil() {
		return org.specapi.ModelUtil.class;
	}
	
	public Class<? extends OutputConfigurationProvider> bindOutputConfigurationProvider() {
		return org.specapi.generator.SpecApiOutputConfigurationProvider.class;
	}
	
	public Class<? extends PluginLoader> bindPluginLoader() {
		return org.specapi.plugins.PluginLoader.class;
	}
}
